// ---------------------------------------------------------------------------
// Readiness-building resource catalogue (curated).
//
// Real, external tools/frameworks/templates that help an organisation BUILD
// readiness, mapped to readiness dimensions (R1-R12). Curated by the project
// team from a structured search + known tools.
// See docs/decisions/0005-readiness-resources.md.
// ---------------------------------------------------------------------------

export interface ReadinessResource {
  id: string;
  title: string;
  publisher: string;
  url: string;
  type: string;
  /** Readiness dimensions this resource helps build (e.g. ["R3", "R6"]). */
  dimensions: string[];
  note?: string;
}

export const readinessResources: ReadinessResource[] = [
  { id: "ai-readiness-checklist", title: "The AI Readiness Checklist", publisher: "CERSI-AI / University of Birmingham", url: "https://www.cersi-ai.org/the-ai-readiness-checklist/", type: "Checklist / framework", dimensions: ["R1", "R4", "R7", "R9", "R10", "R11"], note: "A companion harms-and-controls readiness checklist for a specific AI tool (NHS England / Health Foundation funded; in public consultation). Interactive prototype at aireadiness.uk." },
  { id: "thinking-about-whether-a-medical-device-will-meet-", title: "Thinking about whether a medical device will meet your needs", publisher: "NHS England/NICE/MHRA/CQC/HRA", url: "https://www.digitalregulations.innovation.nhs.uk/regulations-and-guidance-for-adopters/all-adopters-guidance/thinking-about-whether-a-medical-device-will-meet-your-needs/", type: "Guidance", dimensions: ["R1"] },
  { id: "digital-technology-assessment-criteria-dtac", title: "Digital Technology Assessment Criteria (DTAC)", publisher: "NHS England Digital", url: "https://digital.nhs.uk/services/digital-technology-assessment-criteria-dtac", type: "Framework/checklist", dimensions: ["R3", "R6", "R9"] },
  { id: "nice-evidence-standards-framework-esf-for-dhts", title: "NICE Evidence Standards Framework (ESF) for DHTs", publisher: "NICE", url: "https://www.nice.org.uk/what-nice-does/digital-health/evidence-standards-framework-esf-for-digital-health-technologies", type: "Standard/framework", dimensions: ["R4", "R7", "R8", "R9", "R10", "R11"] },
  { id: "iso-iec-42001-2023-ai-management-systems", title: "ISO/IEC 42001:2023 \u2014 AI management systems", publisher: "ISO/IEC", url: "https://www.iso.org/standard/42001", type: "Standard (certifiable)", dimensions: ["R1", "R4", "R7", "R8", "R9", "R11"] },
  { id: "provider-data-quality-assurance-framework-parts-1-", title: "Provider Data Quality Assurance Framework (Parts 1 & 2)", publisher: "NHS England Digital", url: "https://digital.nhs.uk/data-and-information/data-tools-and-services/data-services/data-quality/framework-for-providers-part-1", type: "Framework/checklist", dimensions: ["R2", "R3", "R6"] },
  { id: "data-quality-maturity-index-dqmi", title: "Data Quality Maturity Index (DQMI)", publisher: "NHS England Digital", url: "https://digital.nhs.uk/data-and-information/data-tools-and-services/data-services/data-quality#provider-data-quality-assurance-framework", type: "Tool/standard", dimensions: ["R2"] },
  { id: "nhs-standards-directory", title: "NHS Standards Directory", publisher: "NHS England Digital", url: "https://digital.nhs.uk/services/nhs-standards-directory", type: "Standard/directory", dimensions: ["R2", "R6"] },
  { id: "data-protection-impact-assessments-dpias-detailed-", title: "Data Protection Impact Assessments (DPIAs) \u2014 detailed guidance", publisher: "ICO", url: "https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/accountability-and-governance/data-protection-impact-assessments-dpias/", type: "Guidance/template", dimensions: ["R3"] },
  { id: "data-sharing-a-code-of-practice", title: "Data sharing: a code of practice", publisher: "ICO", url: "https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-sharing/data-sharing-a-code-of-practice/", type: "Guidance/code", dimensions: ["R3"] },
  { id: "data-security-and-protection-toolkit-dspt", title: "Data Security and Protection Toolkit (DSPT)", publisher: "NHS England Digital", url: "https://digital.nhs.uk/cyber-and-data-security/cyber-security-services/data-security-and-protection-toolkit", type: "Tool/standard", dimensions: ["R3"] },
  { id: "cyber-assessment-framework-caf", title: "Cyber Assessment Framework (CAF)", publisher: "NCSC", url: "https://www.ncsc.gov.uk/collection/cyber-assessment-framework", type: "Framework", dimensions: ["R3"] },
  { id: "cyber-essentials", title: "Cyber Essentials", publisher: "NCSC (IASME)", url: "https://www.ncsc.gov.uk/cyberessentials/overview", type: "Standard/certification", dimensions: ["R3"] },
  { id: "guidance-on-the-use-of-ai-enabled-ambient-scribing", title: "Guidance on the use of AI-enabled ambient scribing products", publisher: "NHS England", url: "https://www.england.nhs.uk/long-read/guidance-on-the-use-of-ai-enabled-ambient-scribing-products-in-health-and-care-settings/", type: "Guidance", dimensions: ["R1", "R3", "R4", "R7", "R9", "R12"] },
  { id: "general-staff-training-and-product-specific-user-t", title: "General staff training and product-specific user training for DHTs", publisher: "AIDRS (NHS England)", url: "https://www.digitalregulations.innovation.nhs.uk/regulations-and-guidance-for-adopters/all-adopters-guidance/general-staff-training-and-product-specific-user-training-for-digital-healthcare-technologies/", type: "Guidance", dimensions: ["R4", "R7"] },
  { id: "guidance-on-ai-and-data-protection-incl-annex-a-fa", title: "Guidance on AI and data protection (incl. Annex A: Fairness)", publisher: "ICO", url: "https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/artificial-intelligence/guidance-on-ai-and-data-protection/", type: "Guidance", dimensions: ["R1", "R3", "R10"] },
  { id: "planning-for-local-validation-and-integrating-a-di", title: "Planning for local validation and integrating a digital technology", publisher: "AIDRS (MHRA)", url: "https://www.digitalregulations.innovation.nhs.uk/regulations-and-guidance-for-adopters/all-adopters-guidance/planning-for-local-validation-and-integrating-a-digital-technology/", type: "Guidance", dimensions: ["R5"] },
  { id: "tripod-ai-statement", title: "TRIPOD+AI statement", publisher: "Collins et al., BMJ 2024", url: "https://www.bmj.com/content/385/bmj-2023-078378", type: "Standard/checklist", dimensions: ["R5"] },
  { id: "decide-ai", title: "DECIDE-AI", publisher: "Vasey et al., Nature Medicine 2022", url: "https://www.nature.com/articles/s41591-022-01772-9", type: "Standard/checklist", dimensions: ["R5"] },
  { id: "clinical-risk-management-standards-dcb0129-dcb0160", title: "Clinical Risk Management Standards DCB0129 / DCB0160", publisher: "NHS England Digital", url: "https://digital.nhs.uk/services/clinical-safety/clinical-risk-management-standards", type: "Standard", dimensions: ["R9"] },
  { id: "complying-with-nhs-digital-clinical-risk-managemen", title: "Complying with NHS Digital clinical risk management standards (adopter guide)", publisher: "AIDRS (NHS England)", url: "https://www.digitalregulations.innovation.nhs.uk/regulations-and-guidance-for-adopters/all-adopters-guidance/complying-with-nhs-digital-clinical-risk-management-standards/", type: "Guidance", dimensions: ["R9"] },
  { id: "interoperability-good-practice-guidelines", title: "Interoperability (Good practice guidelines)", publisher: "NHS England", url: "https://www.england.nhs.uk/long-read/interoperability/", type: "Guidance", dimensions: ["R6"] },
  { id: "quality-service-improvement-and-redesign-qsir-tool", title: "Quality, Service Improvement and Redesign (QSIR) tools", publisher: "NHS England", url: "https://www.england.nhs.uk/quality-service-improvement-and-redesign-qsir-tools/", type: "Toolkit/guidance", dimensions: ["R7"] },
  { id: "planning-and-implementing-real-world-ai-evaluation", title: "Planning and implementing real-world AI evaluations (AI Award lessons)", publisher: "NHS England", url: "https://www.england.nhs.uk/long-read/planning-and-implementing-real-world-ai-evaluations-lessons-from-the-ai-in-health-and-care-award/", type: "Guidance", dimensions: ["R8"] },
  { id: "guidance-on-the-impact-evaluation-of-ai-interventi", title: "Guidance on the impact evaluation of AI interventions (Magenta Book AI annex)", publisher: "HM Treasury Evaluation Task Force", url: "https://assets.publishing.service.gov.uk/media/672c84ebbd79990dfa67cab4/2024-11-05_Guidance_on_the_impact_evaluation_of_AI_interventions_FINAL_PDF_WITH_ACCESSIBILITY_CHANGES.pdf", type: "Guidance/standard", dimensions: ["R8"] },
  { id: "dcb0160-clinical-risk-management-in-deployment-use", title: "DCB0160: Clinical Risk Management in Deployment/Use of Health IT", publisher: "NHS England Digital", url: "https://digital.nhs.uk/data-and-information/information-standards/information-standards-and-data-collections-including-extractions/publications-and-notifications/standards-and-collections/dcb0160-clinical-risk-management-its-application-in-the-deployment-and-use-of-health-it-systems", type: "Standard (mandatory)", dimensions: ["R9"] },
  { id: "digital-clinical-safety-training-essentials-practi", title: "Digital Clinical Safety training (Essentials \u2192 Practitioner/CSO)", publisher: "NHS England Digital", url: "https://digital.nhs.uk/services/clinical-safety/clinical-risk-management-training", type: "Training", dimensions: ["R9"] },
  { id: "digital-clinical-safety-assurance", title: "Digital clinical safety assurance", publisher: "NHS England", url: "https://www.england.nhs.uk/long-read/digital-clinical-safety-assurance/", type: "Guidance", dimensions: ["R9"] },
  { id: "software-and-ai-as-a-medical-device-guidance-incl-", title: "Software and AI as a Medical Device \u2014 guidance (incl. GMLP)", publisher: "MHRA", url: "https://www.gov.uk/government/publications/software-and-artificial-intelligence-ai-as-a-medical-device", type: "Guidance/standard", dimensions: ["R11"] },
  { id: "algorithmic-transparency-recording-standard-atrs-h", title: "Algorithmic Transparency Recording Standard (ATRS) Hub + template", publisher: "GDS / DSIT", url: "https://www.gov.uk/government/collections/algorithmic-transparency-recording-standard-hub", type: "Standard+template", dimensions: ["R10"] },
  { id: "standing-together-recommendations-data-diversity-i", title: "STANDING Together Recommendations (data diversity, inclusivity)", publisher: "STANDING Together (UHB NHS FT / NHS AI Lab)", url: "https://www.datadiversity.org/recommendations", type: "Standard/guidance", dimensions: ["R10", "R11"] },
  { id: "ai-and-data-protection-risk-toolkit", title: "AI and Data Protection Risk Toolkit", publisher: "ICO", url: "https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/artificial-intelligence/guidance-on-ai-and-data-protection/ai-and-data-protection-risk-toolkit/", type: "Toolkit/checklist", dimensions: ["R1", "R3", "R4", "R7", "R8", "R10", "R11"] },
  { id: "monitoring-the-safety-and-effectiveness-of-digital", title: "Monitoring the safety and effectiveness of digital technologies (real-world monitoring)", publisher: "AIDRS (NHS England)", url: "https://www.digitalregulations.innovation.nhs.uk/regulations-and-guidance-for-adopters/all-adopters-guidance/monitoring-the-safety-and-effectiveness-of-digital-technologies-real-world-monitoring/", type: "Guidance", dimensions: ["R11"] },
  { id: "a-buyer-s-guide-to-ai-in-health-and-care-assessmen", title: "A Buyer's Guide to AI in Health and Care + assessment template", publisher: "NHS England / NHS AI Lab", url: "https://digital.nhs.uk/services/ai-knowledge-repository/develop-ai/a-buyers-guide-to-ai-in-health-and-care", type: "Guidance+template", dimensions: ["R3", "R5", "R7", "R10", "R11", "R12"] },
  { id: "guidelines-for-ai-procurement", title: "Guidelines for AI Procurement", publisher: "DSIT (Office for AI) / gov.uk", url: "https://www.gov.uk/government/publications/guidelines-for-ai-procurement/guidelines-for-ai-procurement", type: "Guidance", dimensions: ["R12"] },
  { id: "nist-ai-risk-management-framework-ai-rmf-1-0", title: "NIST AI Risk Management Framework (AI RMF 1.0)", publisher: "NIST", url: "https://www.nist.gov/itl/ai-risk-management-framework", type: "Framework (voluntary, US)", dimensions: ["R1", "R3", "R4", "R5", "R6", "R8", "R10", "R11"] },
  { id: "iso-iec-42005-2025-ai-system-impact-assessment", title: "ISO/IEC 42005:2025 \u2014 AI system impact assessment", publisher: "ISO/IEC", url: "https://www.iso.org/standard/42005", type: "Standard/guidance", dimensions: ["R1", "R10"] },
  { id: "chai-responsible-ai-checklists", title: "CHAI Responsible AI Checklists", publisher: "Coalition for Health AI (CHAI)", url: "https://www.chai.org/workgroup/responsible-ai/responsible-ai-checklists-raic", type: "Framework/standard (US)", dimensions: ["R1", "R4", "R5", "R8", "R10", "R11", "R12"] },
  { id: "ethics-governance-of-ai-for-health-2021", title: "Ethics & governance of AI for health (2021)", publisher: "World Health Organization", url: "https://www.who.int/publications/i/item/9789240029200", type: "Guidance (ethics)", dimensions: ["R3", "R10"] },
  { id: "ethics-governance-of-ai-for-health-guidance-on-lar", title: "Ethics & governance of AI for health: guidance on large multi-modal models (2024)", publisher: "World Health Organization", url: "https://www.who.int/publications/i/item/9789240084759", type: "Guidance (ethics)", dimensions: ["R9", "R10"] },
  { id: "healthcare-ai-governance-maturity-model-systematic", title: "Healthcare AI governance maturity model (systematic review)", publisher: "Hussein et al., npj Digital Medicine 2026", url: "https://pubmed.ncbi.nlm.nih.gov/41673321/", type: "Maturity model (academic)", dimensions: ["R1"] },
  { id: "caldicott-principles-8", title: "Caldicott Principles (8)", publisher: "National Data Guardian", url: "https://www.gov.uk/government/publications/the-caldicott-principles", type: "Principles/guidance", dimensions: ["R3", "R10"] },
  { id: "explaining-decisions-made-with-ai", title: "Explaining decisions made with AI", publisher: "ICO & The Alan Turing Institute", url: "https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/artificial-intelligence/explaining-decisions-made-with-artificial-intelligence/", type: "Guidance", dimensions: ["R4", "R10"] },
  { id: "claim-checklist-for-ai-in-medical-imaging", title: "CLAIM \u2014 Checklist for AI in Medical Imaging", publisher: "Mongan, Moy & Kahn, Radiology: AI 2020", url: "https://pubs.rsna.org/doi/10.1148/ryai.2020200029", type: "Standard/checklist", dimensions: ["R5"] },
  { id: "mi-claim-minimum-information-about-clinical-ai-mod", title: "MI-CLAIM \u2014 Minimum Information about Clinical AI Modeling", publisher: "Norgeot et al., Nature Medicine 2020", url: "https://www.nature.com/articles/s41591-020-1041-y", type: "Standard/checklist", dimensions: ["R5"] },
  { id: "future-ai-international-consensus-guideline", title: "FUTURE-AI international consensus guideline", publisher: "Lekadir et al., BMJ 2025", url: "https://www.bmj.com/content/388/bmj-2024-081554", type: "Guidance/framework", dimensions: ["R5", "R10", "R11"], note: "Six principles: fairness, universality, traceability, usability, robustness, explainability" },
  { id: "guidelines-and-standard-frameworks-for-ai-in-medic", title: "Guidelines and standard frameworks for AI in medicine: systematic review", publisher: "Shiferaw et al., JAMIA Open 2025", url: "https://pubmed.ncbi.nlm.nih.gov/39759773/", type: "Evidence review", dimensions: ["R5"] },
  { id: "mapping-quality-appraisal-of-ai-reporting-checklis", title: "Mapping & quality appraisal of AI reporting checklists", publisher: "Vinay et al., 2026", url: "https://europepmc.org/article/MED/42007431", type: "Evidence review", dimensions: ["R5"] },
  { id: "nasss-framework-non-adoption-abandonment-scale-up-", title: "NASSS framework (Non-adoption, Abandonment, Scale-up, Spread, Sustainability)", publisher: "Greenhalgh et al., JMIR 2017", url: "https://doi.org/10.2196/jmir.8775", type: "Framework (academic)", dimensions: ["R1", "R7"] },
  { id: "algorithmic-impact-assessment-a-case-study-in-heal", title: "Algorithmic impact assessment: a case study in healthcare", publisher: "Ada Lovelace Institute (with NHS AI Lab)", url: "https://www.adalovelaceinstitute.org/report/algorithmic-impact-assessment-case-study-healthcare/", type: "Methodology/template", dimensions: ["R3", "R10"], note: "Seven-stage AIA used as a data-access condition; built-in patient/public engagement" },
  { id: "uk-standards-for-public-involvement", title: "UK Standards for Public Involvement", publisher: "NIHR (and partners)", url: "https://sites.google.com/nihr.ac.uk/pi-standards/home", type: "Standard/guidance", dimensions: ["R10"] },
  { id: "predetermined-change-control-plan-pccp-for-ai-enab", title: "Predetermined Change Control Plan (PCCP) for AI-enabled device software functions", publisher: "FDA", url: "https://www.fda.gov/regulatory-information/search-fda-guidance-documents/marketing-submission-recommendations-predetermined-change-control-plan-artificial-intelligence", type: "Guidance/standard", dimensions: ["R5", "R9", "R11"], note: "Final, Dec 2024" },
  { id: "good-machine-learning-practice-gmlp-for-medical-de", title: "Good Machine Learning Practice (GMLP) for Medical Device Development", publisher: "FDA / Health Canada / MHRA", url: "https://www.fda.gov/medical-devices/software-medical-device-samd/good-machine-learning-practice-medical-device-development-guiding-principles", type: "Guidance/principles", dimensions: ["R5", "R9", "R11"], note: "10 principles; tri-regulator" },
  { id: "ai-procurement-in-a-box", title: "AI Procurement in a Box", publisher: "World Economic Forum", url: "https://www.weforum.org/publications/ai-procurement-in-a-box/", type: "Toolkit/guidance", dimensions: ["R12"], note: "International equivalent of the DSIT guidelines" },
  { id: "transparency-guidelines", title: "Transparency guidelines", publisher: "Gov UK", url: "https://www.gov.uk/government/publications/machine-learning-medical-devices-transparency-principles", type: "Guidance (ethics)", dimensions: ["R10"] },
  { id: "pre-determined-change-plans", title: "Pre-determined change plans", publisher: "MHRA", url: "https://www.gov.uk/government/publications/predetermined-change-control-plans-for-machine-learning-enabled-medical-devices-guiding-principles", type: "Guidance", dimensions: ["R11"] },
  { id: "data-ethics-toolkit", title: "Data ethics toolkit", publisher: "Gov UK", url: "https://www.gov.uk/government/publications/data-ethics-framework/data-and-ai-ethics-framework", type: "Framework", dimensions: ["R10"] },
  { id: "turing-guidance-to-ethical-ai", title: "Turing guidance to ethical AI", publisher: "Alan Turing Institute", url: "https://www.turing.ac.uk/sites/default/files/2019-06/understanding_artificial_intelligence_ethics_and_safety.pdf", type: "Guidance (ethics)", dimensions: ["R10"] },
  { id: "understanding-artificial-intelligence-ethics-and-s", title: "Understanding artificial intelligence ethics and safety", publisher: "Gov UK", url: "https://www.gov.uk/guidance/understanding-artificial-intelligence-ethics-and-safety", type: "Guidance (ethics)", dimensions: ["R10"] },
  { id: "managing-your-artificial-intelligence-project", title: "Managing your Artificial Intelligence project", publisher: "Gov UK", url: "https://www.gov.uk/guidance/managing-your-artificial-intelligence-project", type: "Guidance", dimensions: ["R1"] },
  { id: "planning-and-preparing-for-your-ai-project", title: "Planning and preparing for your AI project", publisher: "Gov UK", url: "https://www.gov.uk/guidance/planning-and-preparing-for-artificial-intelligence-implementation", type: "Guidance", dimensions: ["R1"] },
  { id: "clinician-checklist-for-assessing-suitability-of-m", title: "Clinician checklist for assessing suitability of machine learning applications in healthcare", publisher: "Scott, Carter, Coiera 2021", url: "https://informatics.bmj.com/content/28/1/e100251", type: "Framework (academic)", dimensions: ["R5", "R7", "R8", "R10", "R11"] },
  { id: "evaluation-of-ai-solutions-in-health-care-organiza", title: "Evaluation of AI Solutions in Health Care Organizations \u2014 The OPTICA Tool", publisher: "Dagan et al 2024", url: "https://ai.nejm.org/doi/10.1056/AIcs2300269", type: "Toolkit/guidance", dimensions: ["R1", "R2", "R3", "R4", "R5", "R6", "R7", "R8", "R9", "R10", "R11"] },
  { id: "the-algorithm-journey-map-a-tangible-approach-to-i", title: "The algorithm journey map: a tangible approach to implementing AI solutions in healthcare", publisher: "Boag et al 2024", url: "https://www.nature.com/articles/s41746-024-01061-4", type: "Guidance", dimensions: ["R1"] },
  { id: "health-equity-across-the-lifecycle", title: "Health equity across the lifecycle", publisher: "Health AI Partnership", url: "https://drive.google.com/file/d/11wnr-OBZPeaxHjh6l-YJy8W1sqi2k7ea/view", type: "Guidance", dimensions: ["R10"] },
];

/** Resources mapped to a given readiness dimension id (e.g. "R5"). */
export function getReadinessResources(dimensionId: string): ReadinessResource[] {
  return readinessResources.filter((r) => r.dimensions.includes(dimensionId));
}
